name: Nova System CI & Auto-Formatter

on:
  push:
    branches: [ main, dev ]

jobs:
  auto-format:
    name: Auto-Format & Fix Styling
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # We need the token to be able to push changes back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js for Prettier
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Prettier and dependencies
        # This assumes package.json exists from our previous step
        run: npm install

      - name: Run Prettier to format Markdown, YAML, and Shell Scripts
        # The --write flag modifies the files in place
        run: ./node_modules/.bin/prettier --write .

      - name: Set up Python for Black and isort
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python formatters
        run: pip install black isort

      - name: Run isort to sort Python imports
        run: isort .

      - name: Run black to format Python code
        run: black .
      
      - name: Commit and push changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: ✨ auto-format code"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"